manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: te9no
      url-base: https://github.com/te9no
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # - name: zmk
    #   remote: urob
    #   revision: v0.2+fix-child-nodes
    #   import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    # - name: zmk-dongle-display
    #   remote: te9no
    #   revision: test
    - name: zmk-dongle-display-view
      remote: te9no
      revision: main
    # - name: zmk-leader-key
    #   remote: urob
    #   revision: v0.2.1 # set to same as ZMK version above
  self:
    path: config